POST http://localhost:3000/movies
Content-Type: application/json

{
      "id": 6,
      "title": "Curso Back-End Web"
}

###########

GET http://localhost:3000/movies/

############

GET http://localhost:3000/movies/2

############

PUT http://localhost:3000/movies/1
Content-Type: application/json

{
      "id": 1,
      "title": "Curso Back-End Web"
}

#######################
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "John Wick",
    "password": 1234
}

#######################
POST http://localhost:3000
Content-Type: application/json

{
        "title": "John Wick",
        "poster": "https://m.media-amazon.com/images/M/MV5BMTU2NjA1ODgzMF5BMl5BanBnXkFtZTgwMTM2MTI4MjE@._V1_.jpg",
        "synopsis": "Lorem ipsum",
        "genres": "Action, Drama",
        "year": "2014", 
        "director": "Chad Stahelski",
        "actors": "Keanu Reeves"
}