POST http://localhost:3000/movies
Content-Type: application/json

{
      "id": 6,
      "title": "Curso Back-End Web"
}

###########

GET http://localhost:3000/movies/

############

GET http://localhost:3000/movies/8

############

PUT  http://localhost:3000/movies/8
Content-Type: application/json

{
      "title": "Curso Back-End Web 5",
       "poster": "https://m.media-amazon.com/images/M/MV5BMTU2NjA1ODgzMF5BMl5BanBnXkFtZTgwMTM2MTI4MjE@._V1_.jpg",
        "synopsis": "Lorem ipsum",
        "genres_id": "Action, Drama",
        "year": "2014", 
        "director": "Christopher Nolan",
        "actors": ["Keanu Reeves", "John Wick"]
}

############

GET http://localhost:3000/users


#######################
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "username": "John Wick",
    "password": 1234,
    "rol": "user"
}

#######################
POST http://localhost:3000/movies
Content-Type: application/json

{
      
        "title": "The Dark Knight7",
        "poster": "https://m.media-amazon.com/images/M/MV5BMTU2NjA1ODgzMF5BMl5BanBnXkFtZTgwMTM2MTI4MjE@._V1_.jpg",
        "synopsis": "Lorem ipsum",
        "genres_id": "Action, Drama",
        "year": "2014", 
        "director": "Christopher Nolan",
        "actors": ["Keanu Reeves", "John Wick"]
}

############

DELETE http://localhost:3000/movies/6